import { auth } from '@/auth';
import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const { message } = await request.json();
    
    // MOCK AI LOGIC
    // In a real app, call OpenAI/Gemini API here.
    // We will parse simple commands for demo purposes.
    
    let responseText = "I received your request.";
    let suggestedTask = null;

    if (message.includes("meeting")) {
       responseText = "I've drafted a meeting task for you.";
       suggestedTask = {
         title: "Meeting",
         type: "SHIFT",
         startTime: new Date().toISOString(),
         endTime: new Date(Date.now() + 3600000).toISOString(), // +1 hour
         memo: "Generated by AI",
         color: "#ff0000"
       };
    } else if (message.includes("deadline")) {
       responseText = "I've noted the deadline.";
       suggestedTask = {
         title: "Project Deadline",
         type: "DEADLINE",
         deadline: new Date(Date.now() + 86400000).toISOString(), // +1 day
         memo: "Generated by AI",
         color: "#000000"
       };
    } else {
        responseText = "Could you specify if it's a meeting or a deadline?";
    }

    return NextResponse.json({ response: responseText, suggestedTask });

  } catch (error) {
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
